pkg_name=fingerprinter
pkg_origin=migration
pkg_version=$(cat ../VERSION)
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=("Apache-2.0")
pkg_upstream_url="http://chef.io"
pkg_scaffolding="migration/scaffolding-chef-infra"
pkg_svc_user=("root")
scaffold_policy_name="Policyfile"
scaffold_policyfile_path="${PLAN_CONTEXT}/../fingerprinter/"
